### PR TITLE
Use #!/usr/bin/ruby in files etc/tls/utils/ instead of ruby1.9.1

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by ibc** [comment]
Hi, while I'm not against this change I don't think there is a good solution for all the cases. When I did it the Debian default "ruby" package was Ruby 1.8. Now there are Ruby 2.X and so on, and which the default Ruby is depends on each OS/distribution.

Scripts under `etc/tls/utils/` are just helpers. They are not installed as "Gem" binaries so the correct `ruby` executable is not automatically set by the Gem installer.

Thanks a lot, but there is no proper solution for this problem so I prefer that each user modifies the script top line to match his `ruby` executable location.

P.S: I would rather `#!/usr/bin/env ruby`

**Comment by roramirez** [comment]
Do you prefer use #!/usr/bin/env ruby ?

I need test what happends when are distinct Ruby version system.

What do you think?

**Comment by ibc** [comment]
`#!/usr/bin/env ruby` will just use the first `ruby` executable in your `PATH`entries.

**Comment by roramirez** [comment]
so ... this could be a better choice.  I send a PL with these change?

**Comment by eljojo** [comment]
To me, ``#!/usr/bin/env ruby`` still makes more sense than the current ``#!/usr/bin/ruby1.9.1``.

@roramirez why not update it to ``#!/usr/bin/env ruby``?

**Comment by ibc** [comment]
Yes please.

**Pull request closed without merging**
